### ISSUE TITLE
Poll for email send status result

### ISSUE THREAD

**Issue by drmmr763** [hafael/azure-mailer-driver#3]
Hello

Okay so this is a bit of a follow up on this previous issue (https://github.com/hafael/azure-mailer-driver/issues/2)

I understand how the azure api is working in essentially an async way. POST the message, immediate 202 response. But the email could still fail later.

I saw examples for the C# implementation that ping the status api. 

https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email-advanced/manually-poll-for-email-status?tabs=connection-string#sending-email-async-and-polling-for-the-email-send-status

In my debugging of my issue I actually implemented this by setting up that second api request and throwing it at the bottom of the sendApi method:

https://github.com/hafael/azure-mailer-driver/blob/main/src/AzureMailerApiTransport.php#L122

Would there be interest in implementing this as maybe an alternate sending method. It may have to go in as a configuration setting as I don't know how else to pass a call to it down from Laravel's `mail::` facade. Basically, it would poll with progressive backoff and throw an exception if it gets a non-success result. 

Thoughts?

**Comment by hafael** [comment]
Hello! This would be a pretty important feature. I think there are some ways to do this. Before talking about them, I will point out the reason for not foreseeing this mode of operation earlier.
With this package installed in my Laravel project, I mass send daily notifications and also send technical support messages. As it is a considerable volume, the submission jobs are submitted to a job queue. I believe most users of this package would use it in a similar way. With that in mind, my alternative proposals would be:

static method
In the same way as explained in the indicated line. I think it would increase the execution time which would depend on the Azure service.

asynchronous method
Using asynchronous methods that could throw an exception.

Laravel Jobs / Events
Because it is an exclusive package for Laravel, I can launch a Job in a certain list, which can be asynchronous or not. Depending on the response, events could be emitted
Running: Retry
Success: Message sent
Error: Log the failure

If you are comfortable and interested in contributing to the code, we could create a co-collaboration section. What do you think? Anyway, I'm already testing these ideas around here.

**Comment by drmmr763** [comment]
Hello

I think it would be worth having almost both of the sync and async methods for this.

I think with a sync based approach (or maybe a function callback?) it would be easier for those who are already running in a background process to use that.

But, you are right for those concerned with performance something that does the immediate send and then raises an event later that can have a listener. 

I'm happy to try to take a stab at contributing some code.

**Comment by hafael** [comment]
Hi @drmmr763  ,

I have been following your report, and I am still in favor of your propositions. It turns out that the email transport logic that was in this repository was transferred to [symfony/azure-mailer](https://github.com/symfony/azure-mailer) and any pull request that considers this logic must be made there. My suggestion is that you use the implementation code contained in this repository as a reference example for using the mailer driver.
